Bondora.Web/Models/EquipmentModel.cs
using System;

namespace Bondora.Web.Models
{
	public class EquipmentModel
	{
		public int Id { get; set; }
		public String Name { get; set; }
		public int DaysRent { get; set; }
	}
}

Bondora.Web/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Bondora.Shared.Dtos;
using Bondora.Shared.Dtos.Requests;
using Bondora.Shared.Dtos.Responses;
using Bondora.Web.Models;
using EasyNetQ;

namespace Bondora.Web.Controllers
{
	public class EquipmentController : Controller
	{
		private readonly IBus _bus;

		private IDictionary<int, EquipmentModel> CartItems
		{
			get
			{
				if (Session[SessionVariables.CartItems] == null)
				{
					Session[SessionVariables.CartItems] =
						new Dictionary<int, EquipmentModel>();
				}
				return Session[SessionVariables.CartItems] as IDictionary<int, EquipmentModel>;
			}
			set { Session[SessionVariables.Equipments] = value; }
		}

		private IEnumerable<EquipmentModel> Equipment
		{
			get
			{
				if (Session[SessionVariables.Equipments] == null)
				{
					Session[SessionVariables.Equipments] =
						_bus
							.Request<EquipmentListRequest, EquipmentListResponse>(new EquipmentListRequest())
							.Equipments
							.Select(e => new EquipmentModel
							{
								Id = e.Id,
								Name = e.Name,
								DaysRent = 0
							});
				}
				return Session[SessionVariables.Equipments] as IEnumerable<EquipmentModel>;
			}
		}

		public EquipmentController(IBus bus)
		{
			_bus = bus;
		}

		public JsonResult GetAllEquipments()
		{
			return Json(Equipment, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetCartEquipments()
		{
			return Json(CartItems.Values, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public HttpStatusCodeResult AddOrUpdateCartItem(EquipmentModel cartItem)
		{
			var cartItems = CartItems;
			if (cartItems.ContainsKey(cartItem.Id))
			{
				if (cartItem.DaysRent == 0)
					cartItems.Remove(cartItem.Id);
				else
					cartItems[cartItem.Id].DaysRent = cartItem.DaysRent;
			}
			else if (cartItem.DaysRent > 0) cartItems.Add(cartItem.Id, cartItem);
			return new HttpStatusCodeResult(HttpStatusCode.OK);
		}

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult GetInvoice()
		{
			if (!CartItems.Any())
				return RedirectToAction("Index");

			var cartDto = new CartDto
			{
				CustomerId = 1,
				CartItems = CartItems.Values
					.Select(c => new CartItemDto
					{
						EquipmentId = c.Id,
						DaysRent = c.DaysRent
					}).ToList()
			};

			var invoice = _bus.Request<CartDto, InvoiceDto>(cartDto);

			var sb = new StringBuilder();
			sb.AppendLine(invoice.Title);
			foreach (var line in invoice.Lines)
			{
				sb.AppendLine(line);
			}
			sb.AppendLine(invoice.Summary);

			var fileName = $"Invoice_{invoice.Number}.txt";
			MemoryStream ms = new MemoryStream();
			StreamWriter sw = new StreamWriter(ms, Encoding.Unicode);
			sw.WriteLine(sb.ToString());
			sw.Flush();
			ms.Seek(0, SeekOrigin.Begin);
			return File(ms, "application/txt", fileName);
		}
	}
}

Bondora.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bondora.Shared.Dtos;

namespace Bondora.Web.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

Bondora.Web/Views/Equipment/Index.cshtml
<script src="@Url.Content("~/Scripts/jquery-2.2.0.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/knockout-3.4.0.js")" type="text/javascript"></script> 
<script src="@Url.Content("~/Scripts/knockout.mapping-latest.js")" type="text/javascript"></script>
@{
	ViewBag.Title = "Available equipments";
}

<h3>Available equipments</h3>
<table>
	<tr>
		<th style="width: 200px">
			Name
		</th>
		<th style="width: 100px;">
			Days to rent
		</th>
	</tr>
	<tbody data-bind="foreach: Equipments">
	<tr>
		<td data-bind="text: Name"></td>
		<td style="padding-left: 5px;"><input style="width: 50px;" data-bind="value: DaysRent"/></td>
		<td><button data-bind="click: $parent.addItem">Add</button></td>
	</tr>
	</tbody>
</table>

<h3>Equipments in cart</h3>
<table>
	<tr>
		<th style="width: 200px">
			Name
		</th>
		<th style="width: 100px;">
			Days to rent
		</th>
	</tr>
	<tbody data-bind="foreach: CartItems">
		<tr>
			<td data-bind="text: Name"></td>
			<td style="padding-left: 5px;" data-bind="text: DaysRent" ></td>
		</tr>
	</tbody>
</table>

@Html.ActionLink("Download invoice", "GetInvoice")

<script src="~/Scripts/ViewModels/CartViewModel.js"></script>

Bondora.Web/Views/Equipment/_EquipmentView.cshtml
@using Bondora.Shared.Dtos

@model EquipmentDto

@using (Ajax.BeginForm("Index", new AjaxOptions {UpdateTargetId = "equipment." + @Model.EquipmentId.ToString()}))
{
	<span id='equipment.\@Model.EquipmentId'></span>
	<table>
		<tr>
			<td width="200">
				@Html.Hidden("EquipmentId", Model.EquipmentId)
				@Html.HiddenFor(m => m.Name)
				@Html.DisplayFor(m => m.Name)
			</td>
			<td>
				<span class="days">
					@Html.TextBoxFor(m => m.DaysRent, new { type = "number", min = "1", style = "width: 50px"})
					days
				</span>
			</td>
			<td>
				<input type="submit" value="Add"/>
			</td>
		</tr>
	</table>
}

Bondora.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h2>Welcome to Bondora Equipment Store</h2>
</div>

Bondora.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Bondora AS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/ko")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bondora Rental Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Store", "Index", "Equipment")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bondora Rental Store</p>
        </footer>
    </div>
</body>
</html>